version: "3.8"

services:
  go-api:
    build:
      context: .                
      dockerfile: go-api/Dockerfile
    ports:
      - "8080:8080"       
    depends_on:
      - python-llm

  python-llm:
    build: ./python-llm
    ports:
      - "11434:11434"
    extra_hosts:
      - "host.docker.internal:host-gateway"   
